"""change max length for the original field

Revision ID: 608ecb0d3e21
Revises: 83848ca5a8a1
Create Date: 2024-10-12 19:12:09.684693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608ecb0d3e21'
down_revision = '83848ca5a8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('original',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('original',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
