"""add nullable for 'short' field

Revision ID: 83848ca5a8a1
Revises: fe014a290c3c
Create Date: 2024-10-11 17:21:23.216919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83848ca5a8a1'
down_revision = 'fe014a290c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
